# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
# Parent CRDs
- bases/multigres.com_multigresclusters.yaml
- bases/multigres.com_tablegroups.yaml
# Template CRDs
- bases/multigres.com_celltemplates.yaml
- bases/multigres.com_coretemplates.yaml
- bases/multigres.com_shardtemplates.yaml
# Child CRDs
- bases/multigres.com_cells.yaml
- bases/multigres.com_shards.yaml
- bases/multigres.com_toposervers.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
